### ISSUE TITLE
自适应模块

### ISSUE THREAD

**Issue by zuikeaideren** [qcraftai/distill-bev#11]
您好，我想问一下你代码中BEV那个自适应模块适用于FPN吗？然后我想问一下这个自适应模块是在哪里呀？谢谢您的回答

**Comment by dingwenli** [comment]
我们没有尝试过在FPN上用自适应模块，但是该思路是可以用在FPN feature上的。自适应模块的定义可以在这里面找到https://github.com/qcraftai/distill-bev/blob/3e8f6a4d7035125c76f2b0a40424d9defcbf5a8a/mmdet3d/models/detectors/bevdet_distill.py#L216-L352
