### ISSUE TITLE
centerpoint_to_bevdet

### ISSUE THREAD

**Issue by DingCodeLab** [qcraftai/distill-bev#14]
Thanks for your work, could you provide the config and ckpt files fro "centerpoint2bevdet"?

**Comment by dingwenli** [comment]
Hi, thank you for your interest. Due to the resource limitation, we don't have the capacity to prepare the config and checkpoint files for release.

**Comment by SHUSHENGQIGUI** [comment]
> Thanks for your work, could you provide the config and ckpt files fro "centerpoint2bevdet"?

hi, i meet the same problem, did you finish bevdet distillation?
