### ISSUE TITLE
State Dict Mismatch Warnings

### ISSUE THREAD

**Issue by Chan-dh** [qcraftai/distill-bev#15]
Hi, thank you very much for your work, but when I tested using the **centerpoint2bevdetpth weights you provided**, the mAP and NDS values were far lower than those mentioned in the paper.

"Terminal output is as follows:"
![image](https://github.com/user-attachments/assets/ff470206-59ce-40a8-90e0-861758870955)
![image](https://github.com/user-attachments/assets/55581ca4-0ac1-45d0-9d54-94a33fe5f8b7)

**Comment by kinux98** [comment]
Hi, how can you solve this problem? I've encountered the same issue.  I tried to evaluate the model performance with following command : python tools/test.py /root/distill-bev/configs/lidar2camera_bev_distillation/centerpoint_pillar_to_bevdepth4d_r50/centerpoint_02pillar_second_secfpn_circlenms_8x4_cyclic_20e_nus_to_bevdepth4d_r50.py ./centerpoint_to_bevdepth.pth --eval mAP                   

but the performance is lower than expected.
