### ISSUE TITLE
Failed in getting the .pkl files

### ISSUE THREAD

**Issue by Lcp9202** [qcraftai/distill-bev#16]
When I run the command as"**python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes –virtual --extra-tag nuscenes**",It prompted "**AssertionError: MMCV==2.0.0 is used but incompatible. Please install mmcv>=1.3.17, <=1.6.0.**"related to the site-package of **mmdt**. Then I installed the mmcv==1.6.0, but it still prompted "AssertionError: MMCV==1.6.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.2.0" related to the site-package of **mmdet3d**.What should I do?
![微信图片_20241031221205](https://github.com/user-attachments/assets/dc79c8ce-9889-42e0-9686-589d043407f9)

**Comment by dingwenli** [comment]
Hi, have you tried using the [Dockerfile](https://github.com/qcraftai/distill-bev/blob/main/docker/Dockerfile) we provided or the pre-built [image](https://hub.docker.com/r/dingwenqcraft/distillbev)?

**Comment by Lcp9202** [comment]
> Hi, have you tried using the [Dockerfile](https://github.com/qcraftai/distill-bev/blob/main/docker/Dockerfile) we provided or the pre-built [image](https://hub.docker.com/r/dingwenqcraft/distillbev)?
I try to use docker in my service but I failed

**Comment by dingwenli** [comment]
Try `pip install mmcv-full==1.6.0 -f https://download.openmmlab.com/mmcv/dist/cu116/torch1.12/index.html` and then `pip install mmdet==2.24.0`
