### ISSUE TITLE
ModuleNotFoundError: No module named 'mmdet3d.core' 

### ISSUE THREAD

**Issue by Lcp9202** [qcraftai/distill-bev#17]
I can't solve this problem

(distillbev) root@interactive38957:/opt/data/private/ditill-bev/distill-bev# python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes –virtual --extra-tag nuscenes
Traceback (most recent call last):
  File "tools/create_data.py", line 12, in <module>
    from data_converter import kitti_converter as kitti
  File "/opt/data/private/ditill-bev/distill-bev/tools/data_converter/kitti_converter.py", line 9, in <module>
    **from mmdet3d.core.bbox import box_np_ops**
**ModuleNotFoundError: No module named 'mmdet3d.core'**

**Comment by dingwenli** [comment]
This is also related to package installation. Please follow [this](https://github.com/qcraftai/distill-bev/blob/main/docs/INSTALL.md) and try our [Dockerfile](https://github.com/qcraftai/distill-bev/blob/main/docker/Dockerfile) or pre-built [image](https://hub.docker.com/r/dingwenqcraft/distillbev) to make sure package installations are successful.

**Comment by Lcp9202** [comment]
> This is also related to package installation. Please follow [this](https://github.com/qcraftai/distill-bev/blob/main/docs/INSTALL.md) and try our [Dockerfile](https://github.com/qcraftai/distill-bev/blob/main/docker/Dockerfile) or pre-built [image](https://hub.docker.com/r/dingwenqcraft/distillbev) to make sure package installations are successful.

CUDA==11.6 pytorch==1.12.1 

I can't use docker in my env,so I installed all the packages using "pip install" in the dockerfile. I am sure that all the packages have benn installed correctly. But some rediculous problem occured such as that, "MMCV==1.6.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.2.0." occured in mmdet3d, "MMCV==2.2.0 is used but incompatible. Please install mmcv>=1.3.17, <1.6.0."occured in mmdet.So which mmcv version should I use? Which version of mmdet and mmdet3d are compatible?

**Comment by dingwenli** [comment]
According to my previous env installation, pip install mmcv-full==1.6.0 -f https://download.openmmlab.com/mmcv/dist/cu116/torch1.12/index.html should be used. The corresponding compatible mmdet should be mmdet==2.24.0.

For this error, **ModuleNotFoundError: No module named 'mmdet3d.core'**, did you use `export PYTHONPATH=$PYTHONPATH:/opt/data/private/ditill-bev/distill-bev` ?
