### ISSUE TITLE
Visual

### ISSUE THREAD

**Issue by dingmiaomiao** [qcraftai/distill-bev#18]
Thanks for your work. We show our results using the code "python test.py config  XXX.pth --show  --show-dir  path"， and get visual results

![Snipaste_2024-11-12_14-04-57](https://github.com/user-attachments/assets/fcc6511f-7990-4585-b4e2-7ad75dd52b17)

your visual results in the paper

![Snipaste_2024-11-12_14-12-32](https://github.com/user-attachments/assets/61d0f552-b584-4856-ae17-35c855eb152e)

How get the same visual results?  Could you provide your visualization program and steps? I found that newer versions of mmdetection3d offer a better visualization program, but the interface has changed, and I can't use it. Do you have any good suggestions?

**Comment by dingwenli** [comment]
Hi, I recommend to check out our code [here](https://github.com/qcraftai/distill-bev/blob/main/tools/analysis_tools/vis.py) to obtain visualizations on the camera view and BEV.
