### ISSUE TITLE
BLOCKed  Training in bevformerDistill 

### ISSUE THREAD

**Issue by Li-Whasaka** [qcraftai/distill-bev#4]
In 4x4090 Training， Tried many times
I run the script _**./scripts/teacher_to_bevformer/exp_lidar_r50.sh**_ ,But the bevformerdistill code ，**It will get stuck when executed here**

> 
> 2023-11-17 13:31:56,509 - mmdet - INFO - initialize ResNet with init_cfg {'type': 'Pretrained', 'checkpoint': 'torchvision://resnet50'}
> 2023-11-17 13:31:56,510 - mmcv - INFO - load model from: torchvision://resnet50
> 2023-11-17 13:31:56,510 - mmcv - INFO - load checkpoint from torchvision path: torchvision://resnet50

-------------------------------------------------------------------------------------------------------------------------------------------------------
**AND the gpu uitils 100% ,gpu memory just 1700MB plus, which is abnormal.**
Here are some warnings，I'm not sure if it's related to this，
> [W ProcessGroupNCCL.cpp:1569] Rank 0 using best-guess GPU  **0/1/2/3** to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device.

Maybe there's no problem with the code and script, because a few days ago, I trained normally with 2 x 4090. BUT now it can't be.

And it's strange that it's normal to train Bevdet distill with 4 x 4090.

the bevformer script

> MLP_WORKER_GPU=4  
> MLP_WORKER_0_HOST=127.0.0.1  
> MLP_ROLE_INDEX=0  
> MLP_WORKER_0_PORT=10235  
> MLP_WORKER_NUM=1 
> 
> TORCH_DISTRIBUTED_DEBUG=DETAIL python -m torch.distributed.launch --nnodes=$MLP_WORKER_NUM --nproc_per_node=$MLP_WORKER_GPU --node_rank=$MLP_ROLE_INDEX  \
> --master_addr=$MLP_WORKER_0_HOST --master_port=$MLP_WORKER_0_PORT  tools/train.py configs/lidar2camera_bev_distillation/teacher_to_bevformer/lidarformer_to_bevformer_nus_1x1conv_r50.py  \
>         --cfg-options checkpoint_config.interval=4  \
>         model.distill_params.fg_feat_loss_weights=[5e-3,]  \
>         model.distill_params.bg_feat_loss_weights=[4e-3,]  \
>         model.distill_params.spatial_loss_weights=[5e-4,]   --launcher pytorch --deterministic

> +---------------------------------------------------------------------------------------+
> | NVIDIA-SMI 545.23.06              Driver Version: 545.23.06    CUDA Version: 12.3     |
> |-----------------------------------------+----------------------+----------------------+
> | GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
> |                                         |                      |               MIG M. |
> |======================================+======================+======================|
> |   0  NVIDIA GeForce RTX 4090        On  | 00000000:17:00.0 Off |                  Off |
> | 30%   57C    P2              96W / 450W |   1787MiB / 24564MiB |    100%      Default |
> |                                         |                      |                  N/A |
> +-----------------------------------------+----------------------+----------------------+
> |   1  NVIDIA GeForce RTX 4090        On  | 00000000:32:00.0 Off |                  Off |
> | 30%   59C    P2              84W / 450W |   1791MiB / 24564MiB |    100%      Default |
> |                                         |                      |                  N/A |
> +-----------------------------------------+----------------------+----------------------+
> |   2  NVIDIA GeForce RTX 4090        On  | 00000000:65:00.0 Off |                  Off |
> |  0%   31C    P2              68W / 450W |   1791MiB / 24564MiB |    100%      Default |
> |                                         |                      |                  N/A |
> +-----------------------------------------+----------------------+----------------------+
> |   3  NVIDIA GeForce RTX 4090        On  | 00000000:66:00.0 Off |                  Off |
> |  0%   47C    P2              77W / 450W |   1771MiB / 24564MiB |    100%      Default |
> |                                         |                      |                  N/A |
> +-----------------------------------------+----------------------+----------------------+

**Comment by dingwenli** [comment]
This is likely related to the warning [W ProcessGroupNCCL.cpp:1569] you mentioned. I would recommend checking the rank related variables or env variables according to your machine/GPU configuration.
