### ISSUE TITLE
论文中疑惑咨询

### ISSUE THREAD

**Issue by xiaoxusanheyi** [qcraftai/distill-bev#5]
方法3.5部分中特征模仿损失的~M与M有啥区别吗，论文提到是的~M是区域分解掩码M的逻辑补充。能具体讲讲这个~M表示那个区域的掩码吗，
![image](https://github.com/qcraftai/distill-bev/assets/113592382/729511fa-db79-4563-b2b0-f2ada5e4d67f)

**Comment by dingwenli** [comment]
\bar{M} is for the TN region in equation (1). You can find the corresponding code in bevdet_distill.py to see how to obtain M and \bar{M}.

**Comment by xiaoxusanheyi** [comment]
> \bar{M} is for the TN region in equation (1). You can find the corresponding code in bevdet_distill.py to see how to obtain M and \bar{M}.

\bar{M}表示的是公式1中的TN区域，而M表示的是TP or FN区域和 FP区域吗？

**Comment by dingwenli** [comment]
Yes
