### ISSUE TITLE
bevdet4d Data Preparation

### ISSUE THREAD

**Issue by Aloaml** [qcraftai/distill-bev#8]
When I run command according to [https://github.com/qcraftai/distill-bev/blob/main/docs/DATA.md](url) :
```shell
python tools/data_converter/prepare_nuscenes_for_bevdet4d.py
``` 
Wrong message:
```
Traceback (most recent call last):
  File "tools/data_converter/prepare_nuscenes_for_bevdet4d.py", line 120, in <module>
    add_adj_info()
  File "tools/data_converter/prepare_nuscenes_for_bevdet4d.py", line 26, in add_adj_info
    for id in range(len(dataset['infos'])):
KeyError: 'infos'
```
run:
```
print(list(dataset.keys()))
```
out:
```
['metainfo', 'data_list']
```

**There is no key 'infos' in dict 'dataset'.
All command run in docker container.**

**Comment by dingwenli** [comment]
Did you run the following command before that one?
`python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes –virtual --extra-tag nuscenes`
If you have run this one, did you get any error messages?

**Comment by Aloaml** [comment]
> Did you run the following command before that one? `python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes –virtual --extra-tag nuscenes` If you have run this one, did you get any error messages?

Thanks for your reply! You're right. I run `create_data.py`  command in mmdetection3d instead of this project docker container result in something wrong. It could be that there are some issues with the version differences.
