### ISSUE TITLE
Missing config files 

### ISSUE THREAD

**Issue by Aloaml** [qcraftai/distill-bev#9]
https://github.com/qcraftai/distill-bev/blob/3e8f6a4d7035125c76f2b0a40424d9defcbf5a8a/configs/lidar2camera_bev_distillation/centerpoint_pillar_to_bevdepth4d_r50/centerpoint_02pillar_second_secfpn_circlenms_8x4_cyclic_20e_nus_to_bevdepth4d_r50.py#L46

There is no config file `configs/centerpoint/centerpoint_02pillar_second_secfpn_dcn_4x8_cyclic_20e_nus.py`.

And where I can find `centerpoint_to_bevformer` config files?

**Comment by dingwenli** [comment]
Hi, please refer to the config file [configs/dynamic_centerpoint/dynamic_centerpoint_02pillar_second_secfpn_4x8_cyclic_20e_nus.py](https://github.com/qcraftai/distill-bev/blob/3e8f6a4d7035125c76f2b0a40424d9defcbf5a8a/scripts/teacher_to_bevdepth4d/centerpoint2bevdepth.sh#L27C23-L27C115) in [scripts/teacher_to_bevdepth4d/centerpoint2bevdepth.sh](https://github.com/qcraftai/distill-bev/tree/3e8f6a4d7035125c76f2b0a40424d9defcbf5a8a/scripts) for experiments on centerpoint_to_bevdepth. 
For config files to run distillation on BEVFormer, you can find them here https://github.com/qcraftai/distill-bev/tree/3e8f6a4d7035125c76f2b0a40424d9defcbf5a8a/scripts/teacher_to_bevformer
